# Assignment 10

In [2]:
import numpy as np
import scipy as sp
print(np.__version__)
print(sp.__version__)

# Suppress exponential values from printing
np.set_printoptions(suppress=True)

# To get typset effect while printing
from time import sleep
import sys

1.26.3
1.11.4


In [3]:
A = np.array([[9, 6, 0, 0, 0],
             [0, 9, 0, 0, 0],
             [0, 0, 9, 0, 0],
             [0, 0, 0, 9, -5],
             [0, 0, 0, 0, 9]], dtype = "float")

# compute the eigensystem
# Lambda, X
values, vectors = np.linalg.eig(A.copy())

In [4]:
print("~~"*25)
print(f"Eigenvalues:\n{values}\n")
print(f"Eigenvectors:\n{vectors}\n")
print("~~"*25)

sleep(2.5)

print("\nTo verify A*x = lambda*x\n")
sleep(1.5)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Eigenvalues:
[9. 9. 9. 9. 9.]

Eigenvectors:
[[ 1. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  1.]
 [ 0.  0.  0.  0.  0.]]

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

To verify A*x = lambda*x



In [5]:
# Verify the Results
for i in range(len(A)):
    Ax = np.dot(A, vectors[:,i]).round(4)
    lambdaX = np.dot(values[i], vectors[:,i]).round(4)
    print("Ax = ", Ax)
    print("LamdbaX = ", lambdaX)
    print("Ax-lambdaX = ", Ax-lambdaX)

Ax =  [9. 0. 0. 0. 0.]
LamdbaX =  [9. 0. 0. 0. 0.]
Ax-lambdaX =  [0. 0. 0. 0. 0.]
Ax =  [-9.  0.  0.  0.  0.]
LamdbaX =  [-9.  0.  0.  0.  0.]
Ax-lambdaX =  [0. 0. 0. 0. 0.]
Ax =  [0. 0. 9. 0. 0.]
LamdbaX =  [0. 0. 9. 0. 0.]
Ax-lambdaX =  [0. 0. 0. 0. 0.]
Ax =  [0. 0. 0. 9. 0.]
LamdbaX =  [0. 0. 0. 9. 0.]
Ax-lambdaX =  [0. 0. 0. 0. 0.]
Ax =  [0. 0. 0. 9. 0.]
LamdbaX =  [0. 0. 0. 9. 0.]
Ax-lambdaX =  [0. 0. 0. 0. 0.]


In [6]:
B = np.array([[52,4,6,8,9,12],
              [2,54,6,8,9,12],
              [2,4,56,8,9,12],
              [2,4,6,58,9,12],
              [2,4,6,8,59,12],
              [2,4,6,8,9,62]], dtype = "float")

# compute the eigensystem
# Lambda, X
values, vectors = np.linalg.eig(B.copy())

In [7]:
# Print out your results

print("~~"*25)
print(f"Eigenvalues:\n{values}\n")
print(f"Eigenvectors:\n{vectors}\n")
print("~~"*25)

sleep(2.5)

print("\nTo verify A*x = lambda*x\n")
sleep(1.5)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Eigenvalues:
[50. 91. 50. 50. 50. 50.]

Eigenvectors:
[[-0.99348951  0.40824829 -0.46492403 -0.17017947 -0.00808223 -0.08921783]
 [ 0.05094818  0.40824829  0.87315506  0.45743471  0.00650558  0.08803403]
 [ 0.05094818  0.40824829 -0.07322206  0.78960314  0.20415928  0.09844248]
 [ 0.05094818  0.40824829 -0.07322206 -0.2147241  -0.89354981  0.09844248]
 [ 0.05094818  0.40824829 -0.07322206 -0.2147241   0.28934157  0.7193913 ]
 [ 0.05094818  0.40824829 -0.07322206 -0.2147241   0.27579257 -0.66886808]]

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

To verify A*x = lambda*x



In [9]:
# Verify the Results
for i in range(len(B)):
    Bx = np.dot(B, vectors[:,i]).round(4)
    lambdaX = np.dot(values[i], vectors[:,i]).round(4)
    print("Ax = ", Bx)
    print("LamdbaX = ", lambdaX)
    print("Ax-lambdaX = ", Bx-lambdaX)

Ax =  [-49.6745   2.5474   2.5474   2.5474   2.5474   2.5474]
LamdbaX =  [-49.6745   2.5474   2.5474   2.5474   2.5474   2.5474]
Ax-lambdaX =  [0. 0. 0. 0. 0. 0.]
Ax =  [37.1506 37.1506 37.1506 37.1506 37.1506 37.1506]
LamdbaX =  [37.1506 37.1506 37.1506 37.1506 37.1506 37.1506]
Ax-lambdaX =  [0. 0. 0. 0. 0. 0.]
Ax =  [-23.2462  43.6578  -3.6611  -3.6611  -3.6611  -3.6611]
LamdbaX =  [-23.2462  43.6578  -3.6611  -3.6611  -3.6611  -3.6611]
Ax-lambdaX =  [0. 0. 0. 0. 0. 0.]
Ax =  [ -8.509   22.8717  39.4802 -10.7362 -10.7362 -10.7362]
LamdbaX =  [ -8.509   22.8717  39.4802 -10.7362 -10.7362 -10.7362]
Ax-lambdaX =  [0. 0. 0. 0. 0. 0.]
Ax =  [ -0.4041   0.3253  10.208  -44.6775  14.4671  13.7896]
LamdbaX =  [ -0.4041   0.3253  10.208  -44.6775  14.4671  13.7896]
Ax-lambdaX =  [0. 0. 0. 0. 0. 0.]
Ax =  [ -4.4609   4.4017   4.9221   4.9221  35.9696 -33.4434]
LamdbaX =  [ -4.4609   4.4017   4.9221   4.9221  35.9696 -33.4434]
Ax-lambdaX =  [0. 0. 0. 0. 0. 0.]


In [13]:
# Create new eigenvector
vect = vectors[:,3] + vectors[:,4]

# Verify new eigensystem
print("New eigenvector from repeated eigenvalue:\n", vect)
print("Error for new eigenvector from repeated eigenvalues: ", (np.dot(B.copy(), vect) - np.dot(values[3], vect)).round(4))

New eigenvector from repeated eigenvalue:
 [-0.1782617   0.46394029  0.99376242 -1.1082739   0.07461747  0.06106848]
Error for new eigenvector from repeated eigenvalues:  [-0.  0.  0. -0.  0.  0.]
